### ISSUE TITLE
Use of Stub const

### ISSUE THREAD

**Issue by vondervick** [SimonTestNet/SimonTest#31]
Stub const examples, how to use it.

`
beforeEach(() => {
		const cpsStub = {
			getMethodName: (
				arg1: any,
				arg2: any,
				id: any,
				points: any,
				skip: any,
				array: any
			) => ({then: () => ({})})
		};
`

**Comment by ManuelDeLeon** [comment]
There is not prescription on how to use them because they're specific to your tests. You might spy on a method to see that it was called, or you might make it return data specific to a test.

Here's an example of tweaking a stub to use it on a test...

Start of the test:
https://www.youtube.com/watch?v=GJHdE-b9aRg&t=427s

Part where the stub is used:
https://www.youtube.com/watch?v=GJHdE-b9aRg&t=510s

Hope it helps.
