### ISSUE TITLE
Add break lines after statements

### ISSUE THREAD

**Issue by alfredoperez** [SimonTestNet/SimonTest#39]
It will be good to add break lines in the following parts:
- After all the imports
- After variable declarations or mocks
- After `describe`
- After `it`

**Comment by ManuelDeLeon** [comment]
Good idea. I've been hesitant to do implement it because everyone has a different idea of where the breaks should be. That said, I think there's a minimum number of breaks which most people would see it as kinda/sorta okay(ish). 

Update to v1.8.10 to see a conservative amount of breaks in the files =)
